### ISSUE TITLE
Are shortid collisions handled in any way?

### ISSUE THREAD

**Issue by spackmat** [PUGX/shortid-doctrine#3]
Hi,

I read through the code and now I am not sure, if possible ID collisions are detected or actively avoided? I found this [answer on stackoverflow suggesting a method how to actively avoid collisions with existing entities](https://stackoverflow.com/a/29401218). Now I'm wondering, if Doctine itself handles such collisions internally?

Collisions are very rare, but there is a chance rising with every extisting entity, so checking the generated shortid looks like a good idea.

Any ideas on this?

**Comment by garak** [comment]
At this time, there is no mechanism to detect a possible collision.
You could add a listener for `Doctrine\DBAL\Exception\UniqueConstraintViolationException` and regenerate the ShortId

**Comment by spackmat** [comment]
Thanks for the quick answer.

If I would implement such a mechanism within the `ShortidGenerator->generate()` method, which appeals like the right place to me, and I would send a pull request to this repository, Is there a chance that it will be merged?

This would not detect those really really rare race conditions of collisions of two at the same time newly generated entities. But the just really rare case of collisions could be prevented with a simple check.

**Comment by garak** [comment]
If you provide a mechanism to intercept the collision, OK.
But I'm against a solution with a check to prevent it, since it would add a cost (even a small one)

**Comment by spackmat** [comment]
Ah, I see. But I don't have a clou where to intercept such an Exception and regenerate the ID. I'm not that much into the Doctrine internals.

**Comment by garak** [comment]
I'm afraid that is not possible at this level. The `generate` method has the only purpose of returning a valid object, then it doesn't know anything about the entity.
I guess that the control needs to be at an higher level, for example in the Symfony bundle (of course, limited to use with Symfony)
